# Generated by Django 2.0.4 on 2018-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
