# Generated by Django 2.0.4 on 2018-06-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_person_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='updateDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
